version: '3.0'
services:
  ## compose for frontend
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
  ## compose for backend
  backend:
    build: ./backend
    ports:
      - 3001:3001
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ## compose for db
  db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root